apiVersion: apps/v1
kind: Deployment                        #type of kubernetes resource
metadata:
  name: tomcat-deployment
  labels:                 	#deployment label
    app: tomcat
spec:
  replicas: 3              	#create 3 pod
  selector:
    matchLabels:           	# pod label
      app: tomcat
      appname: synchronization
      day: tuesday
  template:                	#container property
    metadata:
      labels:
        app: tomcat
        appname: synchronization
        day: tuesday
    spec:
      containers:
        - name: tomcat
          image: tomcat:10.1.15-jdk21
          ports:
          - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: my-service1
spec:
  selector:          	# selector value should match with
    app: tomcat         	#deployment matchLabels
    appname: synchronization
    day: tuesday
  ports:
   - protocol: TCP
     port: 8080            		 #application port
     targetPort: 8080      		 #application port
  type: NodePort           		 #ClusterIP, NodePort, LoadBalancer 